// Frases patrióticas pré-definidas
export const phrases = [
  "BRASIL ACIMA DE TUDO, DEUS ACIMA DE TODOS",
  "DEUS, FAMÍLIA E LIBERDADE",
  "PÁTRIA AMADA BRASIL",
  "ORDEM E PROGRESSO",
  "LIBERDADE",
  "VERDE E AMARELO É O CORAÇÃO DO BRASIL",
  "NOSSA FORÇA É NOSSA UNIÃO",
  "ORGULHO DE SER BRASILEIRO",
  "UMA NAÇÃO, UM POVO",
  "FÉ, FORÇA E HONRA",
  "PELA ORDEM E PELO PROGRESSO",
  "BRASIL, GIGANTE PELA PRÓPRIA NATUREZA",
  "AMOR, ORDEM E PROGRESSO",
  "A NOSSA BANDEIRA É A NOSSA ALMA",
  "TRABALHO E DEDICAÇÃO PELO BRASIL"
];
